# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import manutencoes_pb2 as manutencoes__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in manutencoes_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GestaoManutencoesStub(object):
    """2. Serviço gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarManutencao = channel.unary_unary(
                '/manutencoes.GestaoManutencoes/CriarManutencao',
                request_serializer=manutencoes__pb2.ManutencaoRequest.SerializeToString,
                response_deserializer=manutencoes__pb2.Manutencao.FromString,
                _registered_method=True)
        self.ListarManutencoes = channel.unary_unary(
                '/manutencoes.GestaoManutencoes/ListarManutencoes',
                request_serializer=manutencoes__pb2.Empty.SerializeToString,
                response_deserializer=manutencoes__pb2.ListaManutencoes.FromString,
                _registered_method=True)
        self.BuscarPorId = channel.unary_unary(
                '/manutencoes.GestaoManutencoes/BuscarPorId',
                request_serializer=manutencoes__pb2.ManutencaoId.SerializeToString,
                response_deserializer=manutencoes__pb2.Manutencao.FromString,
                _registered_method=True)


class GestaoManutencoesServicer(object):
    """2. Serviço gRPC
    """

    def CriarManutencao(self, request, context):
        """RPCs DEVE SER ESCRITAS ASSIM
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarManutencoes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BuscarPorId(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GestaoManutencoesServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarManutencao': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarManutencao,
                    request_deserializer=manutencoes__pb2.ManutencaoRequest.FromString,
                    response_serializer=manutencoes__pb2.Manutencao.SerializeToString,
            ),
            'ListarManutencoes': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarManutencoes,
                    request_deserializer=manutencoes__pb2.Empty.FromString,
                    response_serializer=manutencoes__pb2.ListaManutencoes.SerializeToString,
            ),
            'BuscarPorId': grpc.unary_unary_rpc_method_handler(
                    servicer.BuscarPorId,
                    request_deserializer=manutencoes__pb2.ManutencaoId.FromString,
                    response_serializer=manutencoes__pb2.Manutencao.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'manutencoes.GestaoManutencoes', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('manutencoes.GestaoManutencoes', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GestaoManutencoes(object):
    """2. Serviço gRPC
    """

    @staticmethod
    def CriarManutencao(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manutencoes.GestaoManutencoes/CriarManutencao',
            manutencoes__pb2.ManutencaoRequest.SerializeToString,
            manutencoes__pb2.Manutencao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarManutencoes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manutencoes.GestaoManutencoes/ListarManutencoes',
            manutencoes__pb2.Empty.SerializeToString,
            manutencoes__pb2.ListaManutencoes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BuscarPorId(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manutencoes.GestaoManutencoes/BuscarPorId',
            manutencoes__pb2.ManutencaoId.SerializeToString,
            manutencoes__pb2.Manutencao.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
