# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: manutencoes.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'manutencoes.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11manutencoes.proto\x12\x0bmanutencoes\"f\n\nManutencao\x12\n\n\x02id\x18\x01 \x01(\t\x12\x12\n\nid_veiculo\x18\x02 \x01(\t\x12\x15\n\rplaca_veiculo\x18\x03 \x01(\t\x12\x11\n\tdescricao\x18\x04 \x01(\t\x12\x0e\n\x06status\x18\x05 \x01(\t\"@\n\x10ListaManutencoes\x12,\n\x0bmanutencoes\x18\x01 \x03(\x0b\x32\x17.manutencoes.Manutencao\"\x1a\n\x0cManutencaoId\x12\n\n\x02id\x18\x01 \x01(\t\"=\n\x11ManutencaoRequest\x12\x15\n\rplaca_veiculo\x18\x01 \x01(\t\x12\x11\n\tdescricao\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xea\x01\n\x11GestaoManutencoes\x12J\n\x0f\x43riarManutencao\x12\x1e.manutencoes.ManutencaoRequest\x1a\x17.manutencoes.Manutencao\x12\x46\n\x11ListarManutencoes\x12\x12.manutencoes.Empty\x1a\x1d.manutencoes.ListaManutencoes\x12\x41\n\x0b\x42uscarPorId\x12\x19.manutencoes.ManutencaoId\x1a\x17.manutencoes.Manutencaob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'manutencoes_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MANUTENCAO']._serialized_start=34
  _globals['_MANUTENCAO']._serialized_end=136
  _globals['_LISTAMANUTENCOES']._serialized_start=138
  _globals['_LISTAMANUTENCOES']._serialized_end=202
  _globals['_MANUTENCAOID']._serialized_start=204
  _globals['_MANUTENCAOID']._serialized_end=230
  _globals['_MANUTENCAOREQUEST']._serialized_start=232
  _globals['_MANUTENCAOREQUEST']._serialized_end=293
  _globals['_EMPTY']._serialized_start=295
  _globals['_EMPTY']._serialized_end=302
  _globals['_GESTAOMANUTENCOES']._serialized_start=305
  _globals['_GESTAOMANUTENCOES']._serialized_end=539
# @@protoc_insertion_point(module_scope)
